[package]
name = "lean-buffer-internal"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.31", default-features = false, features = ["full"] }
prettyplease = "0.2.14"
genco = "0.17.5"
flatbuffers = "22.10.26"
darling = "0.20.3"
quote = "1.0.33"
glob = "0.3.1"